package com.example.ui

enum class AppLanguage { BN, EN }

object Translation {
    private val bnMap = mapOf(
        "app_title" to "সঞ্চয়",
        "dashboard" to "ড্যাশবোর্ড",
        "transactions" to "লেনদেন",
        "debts" to "দেনাপাওনা",
        "savings" to "সঞ্চয়",
        "persons" to "ব্যক্তি তালিকা",
        "total_balance" to "মোট ব্যালেন্স",
        "income" to "আয়",
        "expense" to "ব্যয়",
        "i_owe" to "আমার দেনা",
        "owed_to_me" to "আমার পাওনা",
        "recent_tx" to "সাম্প্রতিক লেনদেন",
        "no_tx" to "কোনো লেনদেন পাওয়া যায়নি",
        "no_persons" to "কোনো ব্যক্তি যোগ করা হয়নি",
        "no_savings" to "কোনো সঞ্চয় খাত যোগ করা হয়নি",
        "add_tx" to "নতুন লেনদেন",
        "add_person" to "ব্যক্তি যোগ করুন",
        "add_saving" to "নতুন সঞ্চয় লক্ষ্য",
        "name" to "নাম",
        "phone" to "ফোন নম্বর (ঐচ্ছিক)",
        "amount" to "টাকার পরিমাণ",
        "note" to "নোট / বিবরণ (ঐচ্ছিক)",
        "category" to "খাত / ক্যাটাগরি",
        "type" to "ধরন",
        "person" to "ব্যক্তি",
        "select_person" to "ব্যক্তি নির্বাচন করুন",
        "select_category" to "ক্যাটাগরি নির্বাচন করুন",
        "confirm" to "নিশ্চিত করুন",
        "cancel" to "বাতিল",
        "all" to "সব",
        "history_with" to "এর সাথে লেনদেন ইতিহাস",
        "target" to "লক্ষ্যমাত্রা",
        "saved" to "জমেছে",
        "remaining" to "বাকি আছে",
        "add_money" to "টাকা জমা করুন",
        "delete" to "মুছে ফেলুন",
        "delete_confirm" to "আপনি কি নিশ্চিত যে এটি মুছে ফেলতে চান?",
        "enter_amount" to "পরিমাণ লিখুন",
        "enter_name" to "নাম লিখুন",
        "enter_phone" to "ফোন নম্বর লিখুন",
        "enter_target" to "লক্ষ্যমাত্রা লিখুন",
        "enter_title" to "শিরোনাম লিখুন",
        "tx_type_income" to "আয় (+)",
        "tx_type_expense" to "ব্যয় (-)",
        "tx_type_lend" to "ধার দিলাম",
        "tx_type_borrow" to "ধার নিলাম",
        "tx_type_repay_paid" to "ধার ফেরত দিলাম",
        "tx_type_repay_received" to "ধার ফেরত পেলাম",
        "net_status" to "বর্তমান অবস্থা",
        "settled" to "পরিশোধিত",
        "you_get" to "আপনি পাবেন",
        "you_owe" to "আপনি দেবেন",
        "quick_actions" to "কুইক অ্যাকশন",
        "stats" to "পরিসংখ্যান",
        "details" to "বিস্তারিত",
        "theme" to "থিম",
        "language" to "ভাষা",
        "bengali" to "বাংলা",
        "english" to "English",
        "dark_mode" to "ডার্ক মোড",
        "light_mode" to "লাইট মোড",
        "settings" to "সেটিংস",
        "profile_settings" to "প্রোফাইল সেটিংস",
        "backup_restore" to "ব্যাকআপ ও রিস্টোর",
        "create_backup" to "ব্যাকআপ",
        "restore_backup" to "রিস্টোর",
        "edit" to "এডিট",
        "history" to "ইতিহাস",
        "back" to "পেছনে",
        "debt_repaid" to "ফেরত দিলাম",
        "pawn_repaid" to "ফেরত পেলাম",
        "backup_success" to "ব্যাকআপ সফলভাবে তৈরি হয়েছে!",
        "restore_success" to "ব্যাকআপ সফলভাবে রিস্টোর হয়েছে!",
        "backup_failed" to "ব্যাকআপ ব্যর্থ হয়েছে",
        "restore_failed" to "রিস্টোর ব্যর্থ হয়েছে",
        "profile_saved" to "প্রোফাইল সফলভাবে সংরক্ষিত হয়েছে!",
        "enter_email" to "ইমেইল লিখুন",
        "backup_clipboard" to "ব্যাকআপ কোড কপি করুন",
        "restore_clipboard" to "কোড থেকে রিস্টোর",
        "backup_instructions" to "আপনি অ্যাপের মেমরিতে ব্যাকআপ ফাইল সেভ করতে পারেন অথবা ব্যাকআপ কোড কপি করে রাখতে পারেন।",
        "paste_backup_code" to "ব্যাকআপ কোড এখানে পেস্ট করুন",
        "withdraw" to "উত্তোলন",
        "deposit" to "জমা",
        "select_image" to "ছবি নির্বাচন করুন",
        "error_empty_amount" to "দয়া করে টাকার পরিমাণ লিখুন",
        "error_empty_person" to "দয়া করে ব্যক্তি নির্বাচন করুন",
        "error_empty_title" to "দয়া করে সঞ্চয়ের নাম লিখুন",
        "address" to "ঠিকানা",
        "photo_uri" to "ছবির লিঙ্ক",
        "total_dena" to "মোট দেনা",
        "total_pawn" to "মোট পাওনা",
        "dena" to "দেনা",
        "pawn" to "পাওনা",
        "all" to "সব",
        "all_time" to "সব সময়",
        "today" to "আজকের",
        "this_month" to "এই মাসের",
        "total_income" to "মোট আয়",
        "total_expense" to "মোট ব্যয়",
        "developer_profile" to "ডেভেলপার প্রোফাইল",
        "dev_name" to "শরিফুল ইসলাম",
        "dev_role" to "অ্যান্ড্রয়েড ডেভেলপার",
        "dev_bio" to "আমি একজন শৌখিন অ্যান্ড্রয়েড ডেভেলপার। ক্লিন কোড এবং সুন্দর ইউআই আমার বিশেষত্ব। আধুনিক প্রযুক্তি ব্যবহারে আমি আগ্রহী।",
        "select_profile_photo" to "প্রোফাইল ছবি পরিবর্তন করুন",
        "account" to "অ্যাকাউন্ট",
        "appearance" to "অ্যাপিয়ারেন্স",
        "data_management" to "ডেটা ম্যানেজমেন্ট",
        "about" to "সম্পর্কিত",
        "app_info" to "অ্যাপের তথ্য",
        "version" to "ভার্সন",
        "help_support" to "সহায়তা ও সমর্থন",
        "privacy_policy" to "প্রাইভেসি পলিসি",
        "terms_service" to "ব্যবহারের শর্তাবলী",
        "rate_app" to "অ্যাপ রেটিং দিন",
        "share_app" to "অ্যাপ শেয়ার করুন",
        "contact_dev" to "ডেভেলপারের সাথে যোগাযোগ"
    )

    private val enMap = mapOf(
        "app_title" to "Sanchay",
        "dashboard" to "Dashboard",
        "transactions" to "Transactions",
        "debts" to "Debts & Credits",
        "savings" to "Savings",
        "persons" to "People List",
        "total_balance" to "Total Balance",
        "income" to "Income",
        "expense" to "Expense",
        "i_owe" to "I Owe",
        "owed_to_me" to "Owed to Me",
        "recent_tx" to "Recent Transactions",
        "no_tx" to "No transactions found",
        "no_persons" to "No people added yet",
        "no_savings" to "No savings goals added yet",
        "add_tx" to "Add Transaction",
        "add_person" to "Add Person",
        "add_saving" to "Add Savings Goal",
        "name" to "Name",
        "phone" to "Phone Number (Optional)",
        "amount" to "Amount",
        "note" to "Note / Description (Optional)",
        "category" to "Category",
        "type" to "Type",
        "person" to "Person",
        "select_person" to "Select Person",
        "select_category" to "Select Category",
        "confirm" to "Confirm",
        "cancel" to "Cancel",
        "all" to "All",
        "history_with" to "History with",
        "target" to "Target",
        "saved" to "Saved",
        "remaining" to "Remaining",
        "add_money" to "Add Saved Amount",
        "delete" to "Delete",
        "delete_confirm" to "Are you sure you want to delete this?",
        "enter_amount" to "Enter amount",
        "enter_name" to "Enter name",
        "enter_phone" to "Enter phone number",
        "enter_target" to "Enter target",
        "enter_title" to "Enter title",
        "tx_type_income" to "Income (+)",
        "tx_type_expense" to "Expense (-)",
        "tx_type_lend" to "Lend money",
        "tx_type_borrow" to "Borrow money",
        "tx_type_repay_paid" to "Repay paid",
        "tx_type_repay_received" to "Repay received",
        "net_status" to "Net Status",
        "settled" to "Settled",
        "you_get" to "You will get",
        "you_owe" to "You owe",
        "quick_actions" to "Quick Actions",
        "stats" to "Statistics",
        "details" to "Details",
        "theme" to "Theme",
        "language" to "Language",
        "bengali" to "বাংলা",
        "english" to "English",
        "dark_mode" to "Dark Mode",
        "light_mode" to "Light Mode",
        "settings" to "Settings",
        "profile_settings" to "Profile Settings",
        "backup_restore" to "Backup & Restore",
        "create_backup" to "Backup",
        "restore_backup" to "Restore",
        "edit" to "Edit",
        "history" to "History",
        "backup_success" to "Backup successfully created!",
        "restore_success" to "Backup successfully restored!",
        "backup_failed" to "Backup failed",
        "restore_failed" to "Restore failed",
        "profile_saved" to "Profile successfully saved!",
        "enter_email" to "Enter email",
        "backup_clipboard" to "Copy Backup Code",
        "restore_clipboard" to "Restore from Code",
        "backup_instructions" to "You can save backup file to app private memory or copy the backup code to keep it safe.",
        "paste_backup_code" to "Paste your backup code here",
        "withdraw" to "Withdraw",
        "deposit" to "Deposit",
        "error_empty_amount" to "Please enter amount",
        "error_empty_person" to "Please select a person",
        "error_empty_title" to "Please enter title",
        "address" to "Address",
        "photo_uri" to "Photo URI",
        "total_dena" to "Total Debt",
        "total_pawn" to "Total Credit",
        "dena" to "Debt",
        "pawn" to "Credit",
        "all" to "All",
        "all_time" to "All Time",
        "today" to "Today",
        "this_month" to "This Month",
        "total_income" to "Total Income",
        "total_expense" to "Total Expense",
        "developer_profile" to "Developer Profile",
        "dev_name" to "Shariful Islam",
        "dev_role" to "Android Developer",
        "dev_bio" to "I am a passionate Android developer. Clean code and beautiful UI are my specialties. I love building modern apps.",
        "select_profile_photo" to "Change Profile Photo",
        "account" to "Account",
        "appearance" to "Appearance",
        "data_management" to "Data Management",
        "about" to "About",
        "app_info" to "App Information",
        "version" to "Version",
        "help_support" to "Help & Support",
        "privacy_policy" to "Privacy Policy",
        "terms_service" to "Terms of Service",
        "rate_app" to "Rate App",
        "share_app" to "Share App",
        "contact_dev" to "Contact Developer"
    )

    fun get(key: String, lang: AppLanguage): String {
        return if (lang == AppLanguage.BN) {
            bnMap[key] ?: enMap[key] ?: key
        } else {
            enMap[key] ?: key
        }
    }
}
