name: Cleanup Old Workflow Runs

on:
  workflow_dispatch:

# এই পারমিশন ব্লকটি যুক্ত করুন
permissions:
  actions: write
  contents: read

jobs:
  clean-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
